### ISSUE TITLE
何も設定を行わずに起動するとキャッチされない例外が発生する

### ISSUE THREAD

**Issue by marihachi** [Sagiri-Dev/Sagiri#11]
例外のダイアログが2回出ます。

ver. 1.0.2

1回目
```
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
Sagiri.Exceptions.SagiriException: Configuration any records of null or empty. please check your tokens info.
   at Sagiri.Services.Spotify.Auth.SpotifyAuthenticator._PreAuthentication() in D:\Repository\Sagiri\Sagiri\Services\Spotify\Auth\SpotifyAuthenticator.cs:line 71
   at Sagiri.Services.Spotify.Auth.SpotifyAuthenticator.Initialize() in D:\Repository\Sagiri\Sagiri\Services\Spotify\Auth\SpotifyAuthenticator.cs:line 103
   at Sagiri.Services.Spotify.SpotifyService.Sagiri.Services.Spotify.Interfaces.ISpotifyService.InitializeAsync() in D:\Repository\Sagiri\Sagiri\Services\Spotify\SpotifyService.cs:line 69
   at SagiriUI.Form1.Form1_Load(Object sender, EventArgs e) in D:\Repository\Sagiri\SagiriUI\Form1.cs:line 66
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2回目
```
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sagiri.Services.Spotify.SpotifyService.Sagiri.Services.Spotify.Interfaces.ISpotifyService.Dispose() in D:\Repository\Sagiri\Sagiri\Services\Spotify\SpotifyService.cs:line 156
   at SagiriUI.Form1.Form1_Closing(Object sender, EventArgs e) in D:\Repository\Sagiri\SagiriUI\Form1.cs:line 91
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Asteriskx** [comment]
Spotify のアクセストークン発行、Misskey 側のアクセストークン発行がいります！！！
詳しくは 同梱している release-note を見てもらえると....

**Comment by marihachi** [comment]
例外つかむ方が良いかもという感じです...

**Comment by Asteriskx** [comment]
せやね...

**Comment by Asteriskx** [comment]
トークンない場合は、Message だけ出して設定するように促しますわ

**Comment by marihachi** [comment]
お願いします！

**Comment by Asteriskx** [comment]
ちなみに諸々設定した状態では動かしてみた感じ？

**Comment by marihachi** [comment]
これから動かしてみるよ
